### ISSUE TITLE
OhConnectionException

### ISSUE THREAD

**Issue by dchrostowski** [stevecrozz/optionshouse-api-client#2]
I don't really use python, but I definitely have some idea of what I'm doing.   Not sure what happened here.

  File "oh_test.py", line 8, in <module>
    s.quote('GS')
  File "/usr/local/lib/python2.7/site-packages/optionshouse/session.py", line 163, in quote
    ViewQuoteListRequest(self.authToken, keys, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/optionshouse/session.py", line 295, in request
    return self.issue_request(ohreq)
  File "/usr/local/lib/python2.7/site-packages/optionshouse/session.py", line 301, in issue_request
    raise OhConnectionException('HTTP code: ', e.code)
session.OhConnectionException

**Comment by dchrostowski** [comment]
Well I guess the tests ran OK:

dan@localhost:~/oh_api/optionshouse-api-client/tests$ python test_session.py 
................
----------------------------------------------------------------------
Ran 16 tests in 0.027s

OK


python test_request.py 
...............
----------------------------------------------------------------------
Ran 15 tests in 0.003s

OK

Am I doing something wrong?  Forgive my ignorance of python.

**Comment by krillr** [comment]
Does your optionshouse account have api access?

**Comment by dchrostowski** [comment]
I found out that it doesn't.  I think you need to have at least 10K in your brokerage account.
